BvvTask/Controllers/AppliedController.cs
using BvvTask.Infrastructure;
using BvvTask.Models;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.DependencyInjection;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;

namespace BvvTask.Controllers
{
    /// <summary>
    /// Контроллер запросов к аналогу таблицы tbAgents
    /// </summary>
    [Authorize]
    public class AppliedController: Controller
    {
        private WebSocketProcessor _SocketProcessor;
        private IRepository _Repository;

        public AppliedController(WebSocketProcessor processor, IRepository repo)
        {
            _SocketProcessor = processor;
            _Repository = repo;
        }

        public IActionResult Index() => View("Index", Guid.NewGuid().ToString());

        /// <summary>
        /// Запустим имитацию бурной деятельности
        /// статус будем отслеживать асинхронно на 
        /// клиенте, получая сообщения по WebSocket
        /// </summary>
        /// <param name="prms"></param>
        /// <returns></returns>
        public IActionResult PerformTask([FromBody] TaskParams prms)
        {
            var client = _SocketProcessor.GetClient(prms.UserId);
            CancellationTokenSource cancellationSource = new CancellationTokenSource();
            client.CancellationSource = cancellationSource;
            var token = cancellationSource.Token;
            // Это наша вставка строк, мы ее будем отслеживать по WebSocket
            var scope = HttpContext.RequestServices.CreateScope();
            Task.Run(async () =>
            {
                using (scope)
                {
                    var repository = scope.ServiceProvider.GetRequiredService<IRepository>();
                    var rand = new Random();
                    for (int i = 0; i < prms.RowsCount; i++)
                    {
                        if (token.IsCancellationRequested)
                            break;
                        await client.Send(new WebSocketResult
                        {
                            completed = false,
                            progress = (int)((float)i / prms.RowsCount * 100)
                        });
                        var agent = new Agent();
                        agent.Data = rand.Next().ToString("X2");
                        agent.PrimaryObject = rand.Next().ToString("X2");
                        agent.SecondaryObject = rand.Next().ToString("X2");
                        agent.Resources = rand.Next().ToString("X2");
                        repository.SaveAgent(agent);
                        //Мы же не будем сохранять 1 секунду, продлим задачу
                        await Task.Delay(1000);
                    }
                }
                if (!token.IsCancellationRequested)
                {
                    await client.Send(new WebSocketResult
                    {
                        completed = true,
                        progress = 100
                    });
                }
            }, token);
            return Json(new { started = true });
        }

        [Route("agents")]
        [HttpGet]
        public IEnumerable<Agent> Get()
        {
            return _Repository.Agents.ToList();
        }

        [Route("agent")]
        [HttpPost]
        public Agent Post(string values)
        {
            var agent = new Agent();
            JsonConvert.PopulateObject(values, agent);
            _Repository.SaveAgent(agent);
            return agent;
        }

        [Route("agent")]
        [HttpPut]
        public Agent Put(long key, string values)
        {
            var agent = _Repository.Agents.First(a => a.AgentId == key);
            JsonConvert.PopulateObject(values, agent);
            _Repository.SaveAgent(agent);
            return agent;
        }

        [Route("agent")]
        [HttpDelete]
        public bool Delete(long key)
        {
            return _Repository.DeleteAgent(key);
        }
    }
}

BvvTask/Controllers/AuthController.cs
using BvvTask.Models;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace BvvTask.Controllers
{
    public class AuthController: Controller
    {
        private IRepository _Repo;

        public AuthController(IRepository repo)
        {
            _Repo = repo;
        }

        public IActionResult Login(string returnUrl = "/")
        {
            return View(new LoginModel
            {
                ReturnUrl = returnUrl,
                User = new Models.User()
            });
        }

        [HttpPost]
        public async Task<IActionResult> Login(LoginModel model, string returnUrl = "/")
        {
            if (ModelState.IsValid)
            {
                var user = _Repo.Users.FirstOrDefault(u => u.Name == model.User.Name);
                if (user != null)
                {
                    if (model.User.PasswordHash == user.PasswordHash)
                    {
                        var principal = new ClaimsPrincipal();
                        var claimsIdentity = new ClaimsIdentity(new[] { new Claim(ClaimTypes.Name, model.User.Name) }, 
                            CookieAuthenticationDefaults.AuthenticationScheme);
                        principal.AddIdentity(claimsIdentity);
                        await HttpContext.SignInAsync(principal);
                        return Redirect(returnUrl);
                    }
                    else
                    {
                        ModelState.AddModelError(nameof(model.User.Name), $"Wrong password for the user {model.User.Name}");
                    }
                }
                else
                {
                    ModelState.AddModelError(nameof(model.User.Name), $"There is no user {model.User.Name} in the database");
                }
            }
            return View(model);
        }

        public async Task<IActionResult> Logout(string returnUrl = "/")
        {
            await HttpContext.SignOutAsync();
            return Redirect(returnUrl);
        }

        public string AccessDenied()
        {
            return "Access denied";
        }
    }
}

BvvTask/Controllers/HtmlTableController.cs
using BvvTask.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BvvTask.Controllers
{
    /// <summary>
    /// Редактируемое HTML-поле
    /// </summary>
    [Authorize]
    public class HtmlTableController: Controller
    {
        private IRepository _Repository;

        public HtmlTableController(IRepository repo)
        {
            _Repository = repo;
        }

        public IActionResult Index() => View();

        [Route("/Rows")]
        [HttpGet]
        public IEnumerable<HtmlProduct> Get()
        {
            return _Repository.Products.ToList();
        }

        [Route("/Row")]
        [HttpPost]
        public HtmlProduct Post(string values)
        {
            var product = new HtmlProduct();
            JsonConvert.PopulateObject(values, product);
            _Repository.SaveProduct(product);
            return product;
        }

        [Route("/Row")]
        [HttpPut]
        public HtmlProduct Put(long key, string values)
        {
            var product = _Repository.Products.First(p => p.HtmlProductId == key);
            JsonConvert.PopulateObject(values, product);
            _Repository.SaveProduct(product);
            return product;
        }

        [Route("/Row")]
        [HttpDelete]
        public bool Delete(long key)
        {
            return _Repository.DeleteProduct(key);
        }
    }
}

BvvTask/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <meta name="viewport" content="initial-scale=1, shrink-to-fit=no, width=device-width" />
    <meta charset="utf-8" />
    <link rel="stylesheet" asp-href-include="~/lib/css/styles/*.css" />
    <link rel="stylesheet" asp-href-include="~/lib/css/bootstrap*.css" />
    <link rel="stylesheet" href="~/lib/css/font-awesome.css" />
    <link rel="stylesheet" href="~/lib/css/wysiwyg-editor.css" />

    <script src="~/lib/js/jquery-3.2.1.js"></script>
    <script src="~/lib/js/jquery.validate.js"></script>
    <script src="~/lib/js/additional-methods.js"></script>
    <script src="~/lib/js/jquery.validate.unobtrusive.js"></script>
    <script src="~/lib/js/typeahead.jquery.js"></script>
    <script src="~/lib/js/typeahead.bundle.js"></script>
    <script src="~/lib/js/bloodhound.js"></script>
    <script src="~/lib/js/popper-utils.js"></script>
    <script src="~/lib/js/popper.js"></script>
    <script src="~/lib/js/bootstrap.js"></script>
    <script src="~/lib/js/showdown.js"></script>
    <script src="~/lib/js/typeahead.bundle.js"></script>
    <script src="~/lib/js/wysiwyg.js"></script>

    <link href="~/lib/devextreme/css/dx.common.css" rel="stylesheet" />
    <link href="~/lib/devextreme/css/dx.light.css" rel="stylesheet" />
    <script src="~/lib/devextreme/js/dx.all.js"></script>
    <script src="~/lib/devextreme-aspnet-data/js/dx.aspnet.data.js"></script>
    <script src="~/lib/devextreme/js/dx.aspnet.mvc.js"></script>

    <style>
        #html-editor-container {
            position: fixed;
            top: 0;
            left: 0;
            width: 100%;
            height: 100%;
            background: #f7f4bd;
            z-index: 100;
            padding: 100px;
        }
        #editor {
            width: 100%;
            background-color: #fefefe;
        }
        #end-edit {
            margin-top: 20px;
        }
    </style>
</head>
<body class="container">
    @if (User?.Identity?.IsAuthenticated == true)
    {
    <div class="card mt-4">
        <div class="row">
            <div class="col-4">
                Signed in as: @User.Identity.Name <a asp-action="Logout" asp-controller="Auth" asp-route-returnUrl="@Context.Request.Path.Value">Logout</a>
            </div>
            <div class="col-4">
                <a asp-action="Index" asp-controller="Applied">(Task Part I) Go to async agents</a>
            </div>
            <div class="col-4">
                <a asp-action="Index" asp-controller="HtmlTable">(Task Part II) Go to the HTML table</a>
            </div>
        </div>
    </div>
    }
    <div class="mt-4">
        @RenderBody()
    </div>
</body>
</html>